# Generated by Django 4.2.1 on 2023-06-01 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id_acao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id_carteira', models.AutoField(primary_key=True, serialize=False)),
                ('valor_aplicado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('saldo_bruto', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acao')),
                ('id_carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carteira')),
            ],
        ),
        migrations.CreateModel(
            name='Dividendo',
            fields=[
                ('id_dividendo', models.AutoField(primary_key=True, serialize=False)),
                ('data_dividendo', models.DateField()),
                ('valor_dividendo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantidade', models.IntegerField()),
                ('id_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acao')),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id_cotacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_cotacao', models.DateField()),
                ('valor_cotacao', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acao')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('data_compra', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acao')),
                ('id_carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carteira')),
            ],
        ),
        migrations.AddField(
            model_name='carteira',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
    ]
